// Build-time tool: converts geoBoundaries TUN ADM1 GeoJSON into compact SVG path data.
// Source: geoBoundaries (www.geoboundaries.org), data © OpenStreetMap contributors, ODbL 1.0.
// Output: public/map-data.js  (SVG paths in a 420x820 viewBox, ~1 decimal precision)
const fs = require('fs');
const path = require('path');

const gj = JSON.parse(fs.readFileSync(path.join(__dirname, 'tun-adm1.geojson'), 'utf8'));
console.log('features:', gj.features.length);

// ---- collect bounds ----
let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
function eachPoint(coords, fn) {
  if (typeof coords[0] === 'number') return fn(coords);
  coords.forEach(c => eachPoint(c, fn));
}
gj.features.forEach(f => eachPoint(f.geometry.coordinates, ([x, y]) => {
  if (x < minX) minX = x; if (x > maxX) maxX = x;
  if (y < minY) minY = y; if (y > maxY) maxY = y;
}));
console.log('bounds', minX, minY, maxX, maxY);

// ---- projection: simple equirectangular scaled to viewBox ----
const W = 420;
const latMid = (minY + maxY) / 2;
const kx = Math.cos(latMid * Math.PI / 180); // longitude compression
const spanX = (maxX - minX) * kx;
const spanY = maxY - minY;
const scale = W / spanX;
const H = Math.ceil(spanY * scale);
console.log('viewBox', W, H);

function project([lon, lat]) {
  return [
    +(((lon - minX) * kx) * scale).toFixed(1),
    +(((maxY - lat)) * scale).toFixed(1),
  ];
}

// ---- Douglas-Peucker simplification in projected space ----
function simplify(pts, tol) {
  if (pts.length < 4) return pts;
  const keep = new Array(pts.length).fill(false);
  keep[0] = keep[pts.length - 1] = true;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let maxD = 0, idx = -1;
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay;
    const len2 = dx * dx + dy * dy || 1e-9;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = pts[i];
      let t = ((px - ax) * dx + (py - ay) * dy) / len2;
      t = Math.max(0, Math.min(1, t));
      const ddx = px - (ax + t * dx), ddy = py - (ay + t * dy);
      const d = ddx * ddx + ddy * ddy;
      if (d > maxD) { maxD = d; idx = i; }
    }
    if (maxD > tol * tol) {
      keep[idx] = true;
      stack.push([a, idx], [idx, b]);
    }
  }
  return pts.filter((_, i) => keep[i]);
}

function ringToPath(ring, tol) {
  let pts = ring.map(project);
  pts = simplify(pts, tol);
  if (pts.length < 3) return '';
  let d = `M${pts[0][0]} ${pts[0][1]}`;
  for (let i = 1; i < pts.length; i++) {
    d += `L${pts[i][0]} ${pts[i][1]}`;
  }
  return d + 'Z';
}

function centroidOf(rings) {
  // centroid of largest ring by area
  let best = null, bestArea = -1;
  rings.forEach(ring => {
    let a = 0, cx = 0, cy = 0;
    const p = ring.map(project);
    for (let i = 0; i < p.length - 1; i++) {
      const cross = p[i][0] * p[i + 1][1] - p[i + 1][0] * p[i][1];
      a += cross;
      cx += (p[i][0] + p[i + 1][0]) * cross;
      cy += (p[i][1] + p[i + 1][1]) * cross;
    }
    a /= 2;
    if (Math.abs(a) > bestArea) {
      bestArea = Math.abs(a);
      best = [+(cx / (6 * a)).toFixed(1), +(cy / (6 * a)).toFixed(1)];
    }
  });
  return best;
}

const TOL = 1.2; // px tolerance in viewBox units
const out = [];
gj.features.forEach(f => {
  const name = f.properties.shapeName;
  const g = f.geometry;
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  let d = '';
  const allRings = [];
  polys.forEach(rings => {
    rings.forEach((ring, i) => {
      // keep outer rings; skip tiny holes
      const p = ringToPath(ring, TOL);
      if (p) { d += p; }
      if (i === 0) allRings.push(ring);
    });
  });
  const c = centroidOf(allRings);
  out.push({ name, d, c });
  console.log(name.padEnd(15), 'pathLen:', d.length, 'centroid:', c);
});

const total = out.reduce((s, o) => s + o.d.length, 0);
console.log('total path chars:', total);

const js = `// Generated by tools/build-map.js from geoBoundaries TUN ADM1 (ODbL, © OpenStreetMap contributors)
// viewBox: 0 0 ${W} ${H}
window.TN_MAP = {
  viewBox: "0 0 ${W} ${H}",
  shapes: ${JSON.stringify(out)}
};
`;
fs.mkdirSync(path.join(__dirname, '..', 'public'), { recursive: true });
fs.writeFileSync(path.join(__dirname, '..', 'public', 'map-data.js'), js);
console.log('wrote public/map-data.js', js.length, 'bytes');
